# Compiler
CXX = g++
CXXFLAGS = -std=c++17 -Wall -g

# Paths for Operator Overloading
MAIN_SRC = OOP/main.cpp
OVERLOAD_CPP = OOP/Operator_Overloading/MyString.cpp
OVERLOAD_HPP = OOP/Operator_Overloading/MyString.hpp
OPRUNNER_HPP = OOP/Operator_Overloading/Oprunner.hpp

# Object files
MAIN_OBJ = main.o
OVERLOAD_OBJ = mystring.o

# Target
OP_TARGET = overload_test

# --- Build Rules ---
.PHONY: all overloading run_overloading clean

# Default target
all: overloading

# Compile and link Operator Overloading
overloading: $(MAIN_OBJ) $(OVERLOAD_OBJ)
	$(CXX) $(CXXFLAGS) $^ -o $(OP_TARGET)

# Compile main.cpp
main.o: $(MAIN_SRC) $(OPRUNNER_HPP)
	$(CXX) $(CXXFLAGS) -c $(MAIN_SRC) -o $@

# Compile MyString.cpp
mystring.o: $(OVERLOAD_CPP) $(OVERLOAD_HPP)
	$(CXX) $(CXXFLAGS) -c $(OVERLOAD_CPP) -o $@

# Run
run_overloading: overloading
	./$(OP_TARGET)

# Clean
clean:
	rm -f *.o $(OP_TARGET)

# Paths for Inheritance
INH_CPP = OOP/Inheritance/account.cpp
INH_HPP = OOP/Inheritance/account.hpp
INH_RUNNER = OOP/Inheritance/inrunner.hpp
INH_OBJ = account.o
INH_TARGET = inheritance_test

# Compile Account.cpp
account.o: $(INH_CPP) $(INH_HPP)
	$(CXX) $(CXXFLAGS) -c $(INH_CPP) -o $@

# Build inheritance executable
inheritance: $(MAIN_OBJ) $(INH_OBJ)
	$(CXX) $(CXXFLAGS) $^ -o $(INH_TARGET)

# Run command
.PHONY: run_inheritance
run_inheritance: inheritance
	./$(INH_TARGET)
